### ISSUE TITLE
Road-Lane detection using opencv in Python.

### ISSUE THREAD

**Issue by DrakeEntity** [codePerfectPlus/OpenCv-tutorial#1]
Create Road-lane detection program in openCV using Python.

Some Instructions
- one change on pull request
- If you are new to github flow, check here https://www.dataschool.io/how-to-contribute-on-github/
- Create program under 8. Object detection

**Comment by harshit-saraswat** [comment]
Hey can I do this during hacktober fest?

**Comment by codePerfectPlus** [comment]
Ya sure 
@harshit-saraswat 

Happy Coding,

**Comment by harshit-saraswat** [comment]
> Ya sure
> @harshit-saraswat
> 
> Happy Coding,

Thanks, can you assign this to me?

**Comment by codePerfectPlus** [comment]
- [ ] Assigning Task to @harshit-saraswat
